# Generated by Django 4.0.5 on 2023-02-16 09:42

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_contact_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('secondary_contact_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyAdmin',
        ),
        migrations.DeleteModel(
            name='Mybill',
        ),
        migrations.DeleteModel(
            name='Mybld',
        ),
        migrations.DeleteModel(
            name='Mycart',
        ),
        migrations.DeleteModel(
            name='Mycategory',
        ),
        migrations.DeleteModel(
            name='Myproduct',
        ),
        migrations.DeleteModel(
            name='Myshopkeper',
        ),
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
