# Generated by Django 4.0.5 on 2022-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mybld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeperid', models.IntegerField()),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='pics')),
                ('isdeleted', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mycategory',
            name='shopkeperid',
        ),
    ]
