# Generated by Django 4.0.5 on 2023-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybill',
            name='pincode',
            field=models.TextField(max_length=20),
        ),
    ]
