# Generated by Django 4.0.5 on 2022-12-17 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0002_mybld_remove_mycategory_shopkeperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybld',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
