# Generated by Django 4.0.5 on 2023-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0003_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
