# Generated by Django 4.0.5 on 2023-01-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0004_alter_books_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
