# Generated by Django 4.0.5 on 2023-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
