# Generated by Django 4.0.5 on 2023-01-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0007_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybill',
            name='total',
        ),
    ]
