# Generated by Django 4.0.5 on 2023-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0008_remove_mybill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybill',
            name='productid',
        ),
    ]
