# Generated by Django 4.0.5 on 2023-01-30 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0009_remove_mybill_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybill',
            name='total',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
