# Generated by Django 4.0.5 on 2023-02-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_One', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
