# Generated by Django 4.0.5 on 2022-12-09 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragister',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
