# Generated by Django 4.0.5 on 2022-12-12 06:55

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.TextField(max_length=124)),
                ('password', models.TextField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Mybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=124)),
                ('address', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=40)),
                ('city', models.TextField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('productid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('payment_mode', models.IntegerField()),
                ('billdate', models.DateField(auto_now_add=True, null=True)),
                ('pincode', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('billid', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mycategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='pics')),
                ('shopkeperid', models.IntegerField()),
                ('isdeleted', models.IntegerField(default=0, null=True)),
            ],
        ),
        AddDefaultValue(
            model_name='Mycategory',
            name='isdeleted',
            value='0'
        ),
        migrations.CreateModel(
            name='Myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=124)),
                ('price', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=220)),
                ('categoryid', models.IntegerField()),
                ('shopkeeperid', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('bld', models.TextField(max_length=40)),
                ('stock', models.IntegerField(max_length=40)),
                ('isdeleted', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),     
        AddDefaultValue(
            model_name='Myproduct',
            name='isdeleted',
            value='0'
        ),
        migrations.CreateModel(
            name='Myshopkeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=124)),
                ('email', models.CharField(max_length=60)),
                ('password', models.TextField(max_length=50)),
                ('compneyname', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=40)),
                ('city', models.TextField(max_length=40)),
                ('pincode', models.TextField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=124)),
                ('image', models.ImageField(upload_to='pics')),
                ('isdeleted', models.IntegerField(default=0, null=True)),
            ],
        ),
        AddDefaultValue(
            model_name='Myshopkeper',
            name='isdeleted',
            value='0'
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('password', models.TextField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=40)),
                ('state', models.TextField(max_length=40)),
                ('pincode', models.TextField(max_length=20)),
            ],
        ),
    ]
