# Generated by Django 4.0.5 on 2022-11-25 10:51

from django.db import migrations, models
from django_add_default_value import AddDefaultValue

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('status', models.IntegerField(default=0, max_length=1, null=True)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        AddDefaultValue(model_name='category',name='status',value='0')
    ]
