# Generated by Django 4.0.5 on 2022-12-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorys',
        ),
    ]
