# Generated by Django 4.0.5 on 2022-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_rename_category_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='photo',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
