# Generated by Django 4.0.5 on 2022-12-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_categorys_photo_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='photo',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
