# Generated by Django 4.0.5 on 2022-12-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_categorys_photo_alter_product_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Products',
        ),
    ]
