# Generated by Django 4.0.5 on 2023-01-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=124)),
                ('address', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=40)),
                ('city', models.TextField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('productid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('payment_mode', models.IntegerField()),
                ('billdate', models.DateField(auto_now_add=True, null=True)),
                ('pincode', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
