# Generated by Django 4.0.5 on 2023-01-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('author', models.TextField(max_length=200)),
            ],
        ),
    ]
