# Generated by Django 4.0.5 on 2023-02-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
