# # Generated by Django 4.0.5 on 2022-11-21 12:41

# import datetime
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Category',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('title', models.CharField(max_length=128)),
#                 ('description', models.TextField(max_length=512)),
#                 ('status', models.IntegerField(default=0, max_length=1, null=True)),
#                 ('photo', models.ImageField(upload_to='pics')),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Product',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('categoryid', models.IntegerField()),
#                 ('title', models.CharField(max_length=128)),
#                 ('description', models.TextField(max_length=512)),
#                 ('price', models.IntegerField(default=0)),
#                 ('photo', models.ImageField(upload_to='pics')),
#             ],
#         ),
#         migrations.CreateModel(
#             name='User',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('email', models.TextField(max_length=128)),
#                 ('password', models.TextField(max_length=255)),
#                 ('mobile', models.TextField(max_length=16)),
#                 ('register_at', models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 11, 17, 766299), null=True)),
#             ],
#         ),
#     ]

# Generated by Django 4.0.5 on 2022-11-21 12:28

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('status', models.IntegerField(default=0, max_length=1, null=True)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=128)),
                ('password', models.TextField(max_length=255)),
                ('mobile', models.TextField(max_length=16)),
                ('register_at', models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 11, 17, 766299), null=True)),
            ],
        ),
        
    ]
