# Generated by Django 4.0.5 on 2022-11-22 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0002_mymodel_timestampedmodel_alter_user_register_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='TimestampedModel',
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 55, 9, 176524), null=True),
        ),
    ]
